name: trivy
summary: Aquasecurity Trivy Vulnerability Scanner 
description: |
      Find vulnerabilities, misconfigurations, secrets, SBOM in containers, 
      Kubernetes, code repositories, clouds and more
version: git
grade: stable
base: core20

confinement: strict

plugs:
  files:
    interface: system-files
    read:
    - /

apps:
  trivy:
    command: bin/trivy
    plugs: [home, files, network, network-bind, removable-media]

parts:
  trivy:
    plugin: go
    source-type: git
    source: https://github.com/aquasecurity/trivy
