name: trivy
summary: Aquasecurity Trivy Vulnerability Scanner 
description: |
      Find vulnerabilities, misconfigurations, secrets, SBOM in containers, 
      Kubernetes, code repositories, clouds and more
version: 0.46.0
grade: stable
base: core22

architectures:
- build-on: amd64
- build-on: arm64
- build-on: armhf
- build-on: ppc64el
- build-on: s390x

confinement: strict

plugs:
  dot-aws:
    interface: personal-files
    read:
    - $HOME/.aws
  dot-k8s:
    interface: personal-files
    read:
    - $HOME/.kube

apps:
  trivy:
    command: trivy
    plugs: [home, network, network-bind, dot-k8s, dot-aws]

parts:
  trivy:
    plugin: dump
    source: https://github.com/james-luther/trivy-snap/releases/download/v$SNAPCRAFT_PROJECT_VERSION/trivy_$SNAPCRAFT_PROJECT_VERSION_Linux-$SNAPCRAFT_TARGET_ARCH.tar.gz
