name: trivy
summary: Vulnerability Scanner 
description: |
      Find vulnerabilities, misconfigurations, secrets, SBOM in containers, 
      Kubernetes, code repositories, clouds and more
version: git
grade: stable
base: core20

confinement: devmode

apps:
  trivy:
    command: bin/trivy
    plugs:
      - home
parts:
  trivy:
    plugin: go
    source-type: git
    source: https://github.com/aquasecurity/trivy
