name: trivy
summary: Aquasecurity Trivy Vulnerability Scanner 
description: |
      Find vulnerabilities, misconfigurations, secrets, SBOM in containers, 
      Kubernetes, code repositories, clouds and more
version: 0.37.1
grade: stable
base: core20

architectures:
- build-on: amd64
- build-on: arm64
- build-on: armhf

confinement: strict

apps:
  trivy:
    command: bin/trivy
    plugs: [home, network, network-bind, removable-media]

parts:
  trivy:
    plugin: go
    source-type: git
    source: https://github.com/aquasecurity/trivy
